import { useNavigate } from 'react-router-dom';
import { ArrowLeft, ChevronRight, Download } from 'lucide-react';
import PageLayout from '../components/PageLayout';
import Card from '../components/Card';
import Button from '../components/Button';
import { useAppContext } from '../context/AppContext';
import './InsightsPage.css';

export default function InsightsPage() {
  const navigate = useNavigate();
  const { interviewHistory } = useAppContext();
  
  const recentSession = interviewHistory.length > 0 ? interviewHistory[0] : null;
  const overallScore = recentSession ? recentSession.score : 0;
  
  const getGradeInfo = (score) => {
    if (score === 0) return { label: 'Incomplete Session ⚠️', sub: 'No answers recorded' };
    if (score >= 90) return { label: 'Exceptional Performance 🎉', sub: 'Top 5% of all candidates' };
    if (score >= 80) return { label: 'Great Performance ✨', sub: 'Top 22% of all candidates' };
    if (score >= 70) return { label: 'Solid Performance 👍', sub: 'Top 45% of all candidates' };
    return { label: 'Needs Practice 📈', sub: 'Keep practicing to improve' };
  };
  
  const gradeInfo = getGradeInfo(overallScore);

  const categories = [
    { label: 'Communication',   score: Math.min(overallScore + 5, 100), color: '#006398' },
    { label: 'Technical Depth', score: Math.max(overallScore - 9, 0), color: '#003178' },
    { label: 'Behavioral',      score: Math.min(overallScore + 9, 100), color: '#0d47a1' },
    { label: 'Leadership',      score: Math.max(overallScore - 4, 0), color: '#00429c' },
    { label: 'Problem Solving', score: overallScore, color: '#006398' },
  ];

  const feedback = [
    { type: 'strength', text: 'Good use of the STAR method across behavioral questions.' },
    { type: 'strength', text: 'Clear communication style.' },
    { type: 'improve',  text: 'Deepen technical explanations with specific metrics.' },
  ];

  const handleDownloadInsights = () => {
    if (!recentSession) return;
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>AI Intelligence Brief - ${recentSession.role}</title>
        <style>
          body { font-family: 'Segoe UI', system-ui, sans-serif; padding: 40px; color: #111827; max-width: 800px; margin: 0 auto; background: #f9fafb; }
          .hero { background: linear-gradient(135deg, #003178, #0d47a1); color: white; padding: 40px; border-radius: 24px; margin-bottom: 32px; box-shadow: 0 20px 40px rgba(0,0,0,0.1); }
          .score-val { font-size: 64px; font-weight: 800; margin: 0; }
          .section { background: white; padding: 30px; border-radius: 16px; margin-bottom: 24px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
          h2 { color: #003178; margin-top: 0; font-size: 20px; }
          .bar-row { margin-bottom: 16px; }
          .bar-label { display: flex; justify-content: space-between; margin-bottom: 6px; font-weight: 600; font-size: 14px; }
          .bar-track { height: 8px; background: #e5e7eb; border-radius: 4px; overflow: hidden; }
          .bar-fill { height: 100%; border-radius: 4px; }
          .feedback-item { padding: 12px; border-radius: 8px; margin-bottom: 8px; font-size: 14px; }
          .strength { background: #ecfdf5; color: #065f46; border-left: 4px solid #10b981; }
          .improve { background: #eff6ff; color: #1e40af; border-left: 4px solid #3b82f6; }
        </style>
      </head>
      <body>
        <div class="hero">
          <p style="text-transform:uppercase; letter-spacing:0.1em; font-size:12px; opacity:0.8; margin-bottom:12px">AI Performance Intelligence Brief</p>
          <h1 style="margin:0 0 8px">${recentSession.role}</h1>
          <p style="margin:0; opacity:0.7">${recentSession.company} · ${recentSession.duration}</p>
          <div style="margin-top:32px">
            <p class="score-val">${overallScore}<span style="font-size:24px; opacity:0.6">/100</span></p>
            <p style="margin:4px 0 0; font-weight:600">${gradeInfo.label}</p>
          </div>
        </div>
        
        <div class="section">
          <h2>Category Breakdown</h2>
          ${categories.map(cat => `
            <div class="bar-row">
              <div class="bar-label"><span>${cat.label}</span><span>${cat.score}%</span></div>
              <div class="bar-track"><div class="bar-fill" style="width:${cat.score}%; background:${cat.color}"></div></div>
            </div>
          `).join('')}
        </div>

        <div class="section">
          <h2>AI Strategic Feedback</h2>
          ${feedback.map(f => `
            <div class="feedback-item ${f.type}">
              ${f.type === 'strength' ? '✓' : 'ℹ'} ${f.text}
            </div>
          `).join('')}
        </div>
        
        <p style="text-align:center; font-size:12px; color:#9ca3af; margin-top:40px">
          Generated by Interview Stimulator AI · ${new Date().toLocaleDateString()}
        </p>
      </body>
      </html>
    `;
    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `AI_Insights_${recentSession.role.replace(/\s+/g, '_')}.html`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <PageLayout>
      <div className="insights page-enter">
        <header className="insights__header">
          <div className="insights__header-left">
            <button
              id="btn-back-insights"
              className="insights__back"
              onClick={() => navigate('/dashboard')}
              aria-label="Back to dashboard"
            >
              <ArrowLeft size={20} />
            </button>
            <h1 className="insights__title">AI Insights</h1>
          </div>
          <div className="insights__header-actions">
            <button 
              id="btn-download-insights" 
              className="insights__icon-btn" 
              aria-label="Download Insights"
              onClick={handleDownloadInsights}
              disabled={!recentSession}
            >
              <Download size={18} />
            </button>
          </div>
        </header>

        {/* Overall score hero */}
        <div className="insights__score-hero">
          <div className="insights__score-ring">
            <svg viewBox="0 0 120 120" width="120" height="120">
              <circle cx="60" cy="60" r="52" fill="none" stroke="rgba(255,255,255,0.2)" strokeWidth="8"/>
              <circle
                cx="60" cy="60" r="52"
                fill="none"
                stroke="white"
                strokeWidth="8"
                strokeLinecap="round"
                strokeDasharray={`${(overallScore / 100) * 326.7} 326.7`}
                strokeDashoffset="81.7"
                transform="rotate(-90 60 60)"
              />
            </svg>
            <div className="insights__score-value">
              <span className="insights__score-number">{overallScore}</span>
              <span className="insights__score-unit">/ 100</span>
            </div>
          </div>
          <div className="insights__score-text">
            <p className="insights__score-label">Overall Score</p>
            <p className="insights__score-grade">{gradeInfo.label}</p>
            <p className="insights__score-sub">{gradeInfo.sub}</p>
          </div>
        </div>

        {/* Category breakdown */}
        <section className="insights__section">
          <h2 className="insights__section-title">Category Breakdown</h2>
          <Card className="insights__categories">
            {categories.map(cat => (
              <div key={cat.label} className="insights__category">
                <div className="insights__category-header">
                  <p className="insights__category-label">{cat.label}</p>
                  <p className="insights__category-score">{cat.score}%</p>
                </div>
                <div className="insights__bar-track">
                  <div
                    className="insights__bar-fill"
                    style={{ width: `${cat.score}%`, background: cat.color }}
                  />
                </div>
              </div>
            ))}
          </Card>
        </section>

        {/* AI Feedback */}
        <section className="insights__section">
          <h2 className="insights__section-title">AI Feedback</h2>
          <div className="insights__feedback-list">
            {feedback.map((f, i) => (
              <div key={i} className={`insights__feedback-item insights__feedback-item--${f.type}`}>
                <span className="insights__feedback-icon">
                  {f.type === 'strength' ? '✅' : '⚠️'}
                </span>
                <p className="insights__feedback-text">{f.text}</p>
              </div>
            ))}
          </div>
        </section>

        {/* Actions */}
        <div className="insights__actions">
          <Button
            id="btn-view-full-report"
            variant="primary"
            size="lg"
            fullWidth
            disabled={!recentSession}
            onClick={() => navigate('/report')}
          >
            View Full Report
          </Button>
          <Button
            id="btn-practice-again"
            variant="secondary"
            size="lg"
            fullWidth
            onClick={() => navigate('/interview/setup')}
          >
            Practice Again
          </Button>
        </div>
      </div>
    </PageLayout>
  );
}
